/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/DayNightCycle")]
    [LuaRegisterType(0xc92e1d357730ebfd, typeof(LuaBehaviour))]
    public class DayNightCycle : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "7b8402503c5ff314fabc62b618cb6450";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_floor = default;
        [SerializeField] public UnityEngine.Material m_dayMaterial = default;
        [SerializeField] public UnityEngine.Material m_nightMaterial = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_floor),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_dayMaterial),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_nightMaterial),
            };
        }
    }
}

#endif
