/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/RoleDisplayer")]
    [LuaRegisterType(0xde69bdc6e1e8bd6a, typeof(LuaBehaviour))]
    public class RoleDisplayer : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "e4f0b8851a8ec2743a52560c0483ee32";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Vector3 m_offset = new Vector3(0f, 0f, 0f);

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_offset),
            };
        }
    }
}

#endif
