/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/SimpleTextDisplay")]
    [LuaRegisterType(0x23c740c0b05d6b76, typeof(LuaBehaviour))]
    public class SimpleTextDisplay : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "12d028a8faaeb9d4daca9e36dbef9c60";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_text = "";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_text),
                CreateSerializedProperty(_script.GetPropertyAt(1), null),
            };
        }
    }
}

#endif
