/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/Teleporter")]
    [LuaRegisterType(0x206aebecc516c5e9, typeof(LuaBehaviour))]
    public class Teleporter : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "3edc02e58db5a0f41b91c9a12debc339";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_gameArea = default;
        [SerializeField] public UnityEngine.GameObject m_observationDeck = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_gameArea),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_observationDeck),
            };
        }
    }
}

#endif
