/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/ZoneTraversal")]
    [LuaRegisterType(0x12ecf8aa0fdbbabf, typeof(LuaBehaviour))]
    public class ZoneTraversal : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "1cb3fb90679c5d3418a939780a1f6f5b";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_lobbyArea = default;
        [SerializeField] public UnityEngine.GameObject m_dayArea = default;
        [SerializeField] public UnityEngine.GameObject m_nightArea = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_lobbyArea),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_dayArea),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_nightArea),
            };
        }
    }
}

#endif
